backend:
  name: github
  repo: Bionic-Dongle/test-11ty-deploy   # change if your username/repo is different
  branch: main

media_folder: "assets/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "."
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }