backend:
  name: netlify
  identity_url: https://test11tydeploy.netlify.app/.netlify/identity
  branch: main

media_folder: "assets/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "."
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
